@echo off
echo Setting up Supabase environment variables and running the connection test...

rem Set the environment variables from your .env.local file
set SUPABASE_URL=https://mndtlkbpriytaosstyik.supabase.co
set SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZHRsa2Jwcml5dGFvc3N0eWlrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzY2MTI5OSwiZXhwIjoyMDYzMjM3Mjk5fQ.HY1CWB3TjGXYbMrHDSxovTjvG4OYlC8UoXKF0DO6RAE

echo Environment variables set. Running the test script...
node scripts/test-supabase-connection.js

echo.
echo If you need to run this test manually, use:
echo SUPABASE_URL=https://mndtlkbpriytaosstyik.supabase.co SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZHRsa2Jwcml5dGFvc3N0eWlrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzY2MTI5OSwiZXhwIjoyMDYzMjM3Mjk5fQ.HY1CWB3TjGXYbMrHDSxovTjvG4OYlC8UoXKF0DO6RAE node scripts/test-supabase-connection.js

pause